# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Deploy_Via_SSH

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    types:
      - update-secret

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
#    - env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: webfactory/ssh-agent@v0.7.0
      with:
                  ssh-private-key: |
                        ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: actions/checkout@v3
    - name: Setup SSH Key
      run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - name: set-origin
      run: git remote set-url origin https://ZohaibAkhtar:${{ secrets.REMOTE_DEPLOY_PATH }}@github.com/ZohaibAkhtar/Hello-World.git
    - name: SSH Deploy
      run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} "cd ${{ secrets.REMOTE_DEPLOY_PATH }} && git pull origin main && ./deploy.sh"
